language: python
python:
- '2.7'
install:
- pip install ansible==2.5.0 molecule apache-libcloud pycrypto
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: V1extVruKNTRciwNhB3/unlI3s0PrBiXXY+DT0ropmwNs6tw+bKkE9zaxuALWWu/BtT07qfY970rirIlZtSQxtZITMc+0AZE4sIX3io4Mw31T94KPL/97mUNYAruC/4+LXPe/8NgUkDo61QC0loQU9Ka9/OR8kYXtFbsIVuMrOMjaR6c7/CLv9wXwL2HOrkSvQObSBNfmtSm3LvxhY5L9lOSh5tQ2uQCUOi83lOorqof18InPOc6pcVH7v1qob3ussZcE+Pa7W90vKzMw94qPp5wRXy2NuWlR/g2s9eC5AExO3J2B1GsR0zvjQW2ws0kOEfJuDJdC3aMCL8gdJzTSIHYJm2YhtzWhZP5DvQrCMUD1bRcI0HKGH4FfpdPrULWtq4Xp8XXzB8vBY3irn3LX/uHa4v1k41P4F03/vJjWOYVHsz1W1ZM6ikKu60h4zmFlzkidB2JUawnfjA2xKZcuCUwptl79ECn3ybBeo7sdCUTi0n5LQMPk/ntI/LEHwoY2+XL4j81D/2LGM4IDC0RFsDcVr3BfDU9d9RB4474NHgJ8F4xEW5+Nc+VjJcT2jLRNDo7sVMi2bfMk+pojElhKGQd4p000qhKN5kQvLD1nCSuLUbt87m+f9hknx6vAAGMyOo2YICzYdnxwQ2vyxNRQIwpcgwFOEbOgFGpOJzef6c=
  - secure: Kjzmb38d7TMUWy+q4EStuXMyopoIjrz0830aWf8d5DX3fzJ08lrt/gdp7gBV2JMVN9bMjXOW2I7WbheGQ+1nsfUAfcPI8ozSA9+CK07gDkLFM/zVitwgIlVGvdzykLXbPHSKZB+Nr7XLpvkHktQu7cOt3qfCozm/NvxBGHhLjqlmQz/OzAo/YEwkpL2TpTcWszjVwC0rEA/XeKfCh5Cb9wmnGOIGLShsQhMJ9JG+RI40VcQgqJ+3njqrktParOvhGo3SlVo1p/oHaKN+YtywXSxKlQ1b8Eh8QuiRipI4ichJb3VFhb/yj2kN+gEA8xqCsaO/efvF/e50fZGKq7s9+g+pfTWwb7xBhl2V4TTzqs2iFFXgrPbpeKoabXNg3TggpGKYxLkIE/qBYizQ8Jpvj1AN0jAWzx/P/rTbgSWtfcsAT9LgJQYnwYkjSQk3Wi203mh8A5TJV91v7dYJ9Ic1zT0TIirwmyrInB7jru0/ZRQomNL8MQw/nUIPy9CixYnc5PO9hcsJY9Y6/5IxGC5DCRwQ9P6q+cRDoFDCQDyk3jL40XcEj+54XF/n5SYceAONMzKeu3CgpasQEH/decrP6zfThAdKdMeqUSxgusvGvk1xp7SGzckQHRGaxnkVBNuyJNiIpuGHs2xbKuh9Q2cC6IFuU24xvN/Jh+PgWameCFI=
  - secure: dP6tBRTgx70dSoKOyGoZsxqI872WjN8mu70d1bQ/hZZVpUkvBpJREHSX2alk9ZO4MKzN4FrTH2vAyk2VV4tw9+b8QNlLzhM2fKlQU5iDyX3cxJ8W6iFTYhKfwqenSDlxpJAOOHMGcE7quwtWNSUF20JlSFSJnwFE357duGWMGb5FCKDj+pgKV75s11cKzLFOzhcOrHsSFZ/De22FhrSc4SrNmbbI6WByAkJHRZoFvR6IUgk33dFusVgDmFVhxQWcBtFq/6Gteu1Mh3DJ4ny8rUjVaEQpv1b1ntUm0Sw8SYgK6qH2ejPHUG/l206ru+KL151TsjtR+nF4OlXvS7WchkVF9qXOvZ4t+/A104uDaMr58ZC494bc+X6DY0kYA4YukADCXPlWnqe0kkBKDH5OuGfndqxucdhQvQLxoi4IPIkT2CB0LFaZ84dVqQvjpKJoA/bD8zvuPAbqeCDi2OJwNYo8BhF0fbncsJAwhJowHWmLSHBZUztwXFkZXiCNVkX4WQLTheBRMPrLF6njfzHWMT6ZVjqmSvSHATX39fYRg7G4T4UHiOD/2aJ7BS4qZHa+hophmkdyFx8i6Dct6NlbKTIfghsEWxBIRLSRpfgEouvi/mSI6HDWvnX1hwtGg7+eR8lj26Rr3rIhYZUdJ9G+0nPYV5jVKjKM9puFpPuFqTY=
before_install:
- openssl aes-256-cbc -K $encrypted_677a56b8f0a8_key -iv $encrypted_677a56b8f0a8_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: Nw4tfUD1P9sKp8M3BpE/GZmOnqitqsrypHelJ1UURT0v+jRrOHy4HhI77vKs2RRVSxsiKrGcwlcSnMwmkgNuQdaNASLtsaYjzm6Rtf6CHqzzc/Dy9DIxBXYC5oCkcsJLef1uGYfGFzXRum+NKAFuLsvNZbLiuE2rDeXSyBTZ9AnM1DYqAVd+k12s0T0Rca8Kw5vzyEOn35Rf4y2MjFdbs8NyuzFRLMuOVedNrEFJLioKNDKtglyh0lJ4uU9OjYASg1bJ8TgY1wBgcqSe6vA1CRB/1P0qDJiZdVNCTGmBGwBn9EbwivsA3nzcnfdQbPh2x2VKghrF8BzBJl6qDqBMZBo+Ag9Oc8kKy79BJahOOoJA1DwFYoleURK5vR0ksm2paSjKRbDeXcDcni45id4YVv1dOOGbFIF1EplvcTFNId7DiU/5cURb8NwuUnAF9Qubm7MRAzLvxajp5FEa4VYHtwyxMDP17WDMqh4aH/O/5ir8k31MqUCeJGer5pFUDI9ux8ipFpHCDJaVMqh/1uv+TXjP0cpuDlSdmJJxmdl305chtAeMxSPIGpn85ncrMNQfgfZnBFsDoPl9ePi86/c1kOHpSnLzKScFmj2c7VwKSxNdA6rJMG7rdSbdw8QUsGXVP4SCXRsjIWGlrMFxDtQ5CLnpLgnrVocAWsU/8fc0HdE=
