---
- name: Configure App Server
  hosts: all
  become: true
  tasks:
    - name: Install Ruby packages
      apt:
        name: 
          - ruby-full
          - ruby-bundler
          - build-essential
        state: present
        update-cache: yes
