---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add APT Key for MongoDB repo
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present

    - name: Add MongoDB repo into sources.list
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse 
        state: present
        filename: mongodb-org-3.2.list

    - name: Install MongoDB package
      apt:
        name: mongodb-org
        state: present
        update-cache: yes

    - name: Enable MongoDB autostart
      service:
        name: mongod
        enabled: yes
